name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 New Features'
    labels:
      - 'enhancement'
      - 'feature'

  - title: '🐛 Bugs Fixes'
    labels:
      - 'bug'
      - 'bug_fix'
      - 'fix'

  - title: '📄 Documentation'
    labels:
      - 'documentation'
      - 'docs'

  - title: '💊 Refactoring'
    labels:
      - 'refactoring'
      - 'refactor'

  - title: '🔧 Configuration'
    labels:
      - 'config'
      - 'conf'

references:
  - master
  - v.+

exclude-labels:
  - 'skip-changelog'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES

  ## 👍Contributors
  $CONTRIBUTORS
