name: release-draft

on:
  push:
    branches:
      - master

jobs:
  update-release-draft:
    runs-on: ubuntu-18.04

    steps:
    - name: Update GITHUB release-draft with changelog
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
